# coding: utf-8
#from __future__ import unicode_literals
from unidecode import unidecode
import urlparse,urllib
import unicodedata
from resources.lib.Utils import logMsg
import xbmc,xbmcgui,xbmcaddon,xbmcplugin



def ConversionPays(VidPlayer=None,ContainerID=None):
  Traduction={"ile de l’ascension":"ascension island",
    "andorre":"andorra",
    "emirats arabes unis":"united arab emirates",
    "afghanistan":"afghanistan",
    "antigua-et-barbuda":"antigua & barbuda",
    "anguilla":"anguilla",
    "angleterre":"united kingdom",
    "albanie":"albania",
    "arménie":"armenia",
    "angola":"angola",
    "antarctique":"antarctica",
    "argentine":"argentina",
    "samoa américaines":"american samoa",
    "autriche":"austria",
    "australie":"australia",
    "aruba":"aruba",
    "iles åland":"åland islands",
    "azerbaïdjan":"azerbaijan",
    "bosnie-herzégovine":"bosnia & herzegovina",
    "barbade":"barbados",
    "bangladesh":"bangladesh",
    "belgique":"belgium",
    "burkina faso":"burkina faso",
    "bulgarie":"bulgaria",
    "bahreïn":"bahrain",
    "burundi":"burundi",
    "bénin":"benin",
    "saint-barthélemy":"st. barthélemy",
    "bermudes":"bermuda",
    "brunéi darussalam":"brunei",
    "bolivie":"bolivia",
    "pays-bas caribéens":"caribbean netherlands",
    "brésil":"brazil",
    "bahamas":"bahamas",
    "bhoutan":"bhutan",
    "botswana":"botswana",
    "biélorussie":"belarus",
    "belize":"belize",
    "canada":"canada",
    "iles cocos":"cocos (keeling) islands",
    "congo-kinshasa":"congo - kinshasa",
    "république centrafricaine":"central african republic",
    "congo-brazzaville":"congo - brazzaville",
    "suisse":"switzerland",
    "côte d’ivoire":"côte d’ivoire",
    "iles cook":"cook islands",
    "chili":"chile",
    "cameroun":"cameroon",
    "chine":"china",
    "colombie":"colombia",
    "costa rica":"costa rica",
    "cuba":"cuba",
    "cap-vert":"cape verde",
    "curaçao":"curaçao",
    "ile christmas":"christmas island",
    "chypre":"cyprus",
    "république tchèque":"czech republic",
    "allemagne":"germany",
    "diego garcia":"diego garcia",
    "djibouti":"djibouti",
    "danemark":"denmark",
    "dominique":"dominica",
    "république dominicaine":"dominican republic",
    "algérie":"algeria",
    "ceuta et melilla":"ceuta & melilla",
    "equateur":"ecuador",
    "estonie":"estonia",
    "egypte":"egypt",
    "sahara occidental":"western sahara",
    "erythrée":"eritrea",
    "espagne":"spain",
    "ethiopie":"ethiopia",
    "finlande":"finland",
    "fidji":"fiji",
    "iles malouines":"falkland islands",
    "etats fédérés de micronésie":"micronesia",
    "iles féroé":"faroe islands",
    "france":"france",
    "gabon":"gabon",
    "royaume-uni":"united kingdom",
    "royaume uni":"united kingdom",
    "grenade":"grenada",
    "géorgie":"georgia",
    "guyane française":"french guiana",
    "guernesey":"guernsey",
    "ghana":"ghana",
    "gibraltar":"gibraltar",
    "groenland":"greenland",
    "gambie":"gambia",
    "guinée":"guinea",
    "guadeloupe":"guadeloupe",
    "guinée équatoriale":"equatorial guinea",
    "grèce":"greece",
    "iles géorgie du sud et sandwich du sud":"south georgia & south sandwich islands",
    "guatemala":"guatemala",
    "guam":"guam",
    "guinée-bissau":"guinea-bissau",
    "guyana":"guyana",
    "r.a.s. chinoise de hong kong":"hong kong sar china",
    "honduras":"honduras",
    "croatie":"croatia",
    "haïti":"haiti",
    "hongrie":"hungary",
    "iles canaries":"canary islands",
    "indonésie":"indonesia",
    "irlande":"ireland",
    "israël":"israel",
    "ile de man":"isle of man",
    "inde":"india",
    "territoire britannique de l’océan indien":"british indian ocean territory",
    "irak":"iraq",
    "iran":"iran",
    "islande":"iceland",
    "italie":"italy",
    "jersey":"jersey",
    "jamaïque":"jamaica",
    "jordanie":"jordan",
    "japon":"japan",
    "kenya":"kenya",
    "kirghizistan":"kyrgyzstan",
    "cambodge":"cambodia",
    "kiribati":"kiribati",
    "comores":"comoros",
    "saint-christophe-et-niévès":"st. kitts & nevis",
    "corée du nord":"north korea",
    "corée du sud":"south korea",
    "koweït":"kuwait",
    "iles caïmans":"cayman islands",
    "kazakhstan":"kazakhstan",
    "laos":"laos",
    "liban":"lebanon",
    "sainte-lucie":"st. lucia",
    "liechtenstein":"liechtenstein",
    "sri lanka":"sri lanka",
    "libéria":"liberia",
    "lesotho":"lesotho",
    "lituanie":"lithuania",
    "luxembourg":"luxembourg",
    "lettonie":"latvia",
    "libye":"libya",
    "maroc":"morocco",
    "monaco":"monaco",
    "moldavie":"moldova",
    "monténégro":"montenegro",
    "saint-martin (partie française)":"st. martin",
    "madagascar":"madagascar",
    "iles marshall":"marshall islands",
    "macédoine":"macedonia",
    "mali":"mali",
    "myanmar":"myanmar (burma)",
    "mongolie":"mongolia",
    "r.a.s. chinoise de macao":"macau sar china",
    "iles mariannes du nord":"northern mariana islands",
    "martinique":"martinique",
    "mauritanie":"mauritania",
    "montserrat":"montserrat",
    "malte":"malta",
    "maurice":"mauritius",
    "maldives":"maldives",
    "malawi":"malawi",
    "mexique":"mexico",
    "malaisie":"malaysia",
    "mozambique":"mozambique",
    "namibie":"namibia",
    "nouvelle-calédonie":"new caledonia",
    "niger":"niger",
    "ile norfolk":"norfolk island",
    "nigéria":"nigeria",
    "nicaragua":"nicaragua",
    "pays-bas":"netherlands",
    "norvège":"norway",
    "népal":"nepal",
    "nauru":"nauru",
    "niue":"niue",
    "nouvelle-zélande":"new zealand",
    "oman":"oman",
    "panama":"panama",
    "pérou":"peru",
    "polynésie française":"french polynesia",
    "papouasie-nouvelle-guinée":"papua new guinea",
    "philippines":"philippines",
    "pakistan":"pakistan",
    "pologne":"poland",
    "saint-pierre-et-miquelon":"st. pierre & miquelon",
    "pitcairn":"pitcairn islands",
    "porto rico":"puerto rico",
    "territoires palestiniens":"palestinian territories",
    "portugal":"portugal",
    "palaos":"palau",
    "paraguay":"paraguay",
    "qatar":"qatar",
    "la réunion":"réunion",
    "roumanie":"romania",
    "serbie":"serbia",
    "russie":"russia",
    "rwanda":"rwanda",
    "arabie saoudite":"saudi arabia",
    "iles salomon":"solomon islands",
    "seychelles":"seychelles",
    "soudan":"sudan",
    "suède":"sweden",
    "singapour":"singapore",
    "sainte-hélène":"st. helena",
    "slovénie":"slovenia",
    "svalbard et jan mayen":"svalbard & jan mayen",
    "slovaquie":"slovakia",
    "sierra leone":"sierra leone",
    "saint-marin":"san marino",
    "sénégal":"senegal",
    "somalie":"somalia",
    "suriname":"suriname",
    "soudan du sud":"south sudan",
    "sao tomé-et-principe":"são tomé & príncipe",
    "el salvador":"el salvador",
    "saint-martin":"sint maarten",
    "syrie":"syria",
    "swaziland":"swaziland",
    "tristan da cunha":"tristan da cunha",
    "iles turques-et-caïques":"turks & caicos islands",
    "tchad":"chad",
    "terres australes françaises":"french southern territories",
    "togo":"togo",
    "thaïlande":"thailand",
    "tadjikistan":"tajikistan",
    "tokelau":"tokelau",
    "timor oriental":"timor-leste",
    "turkménistan":"turkmenistan",
    "tunisie":"tunisia",
    "tonga":"tonga",
    "turquie":"turkey",
    "trinité-et-tobago":"trinidad & tobago",
    "tuvalu":"tuvalu",
    "taïwan":"taiwan",
    "tanzanie":"tanzania",
    "ukraine":"ukraine",
    "ouganda":"uganda",
    "iles mineures éloignées des états-unis":"u.s. outlying islands",
    "etats-unis":"united states of america",
    "uruguay":"uruguay",
    "ouzbékistan":"uzbekistan",
    "etat de la cité du vatican":"vatican city",
    "saint-vincent-et-les-grenadines":"st. vincent & grenadines",
    "venezuela":"venezuela",
    "iles vierges britanniques":"british virgin islands",
    "iles vierges des états-unis":"u.s. virgin islands",
    "vietnam":"vietnam",
    "vanuatu":"vanuatu",
    "wallis-et-futuna":"wallis & futuna",
    "samoa":"samoa",
    "kosovo":"kosovo",
    "yémen":"yemen",
    "mayotte":"mayotte",
    "afrique du sud":"south africa",
    "zambie":"zambia",
    "zimbabwe":"zimbabwe"}
      
  windowhome=xbmcgui.Window(10000)
  windowhome.clearProperty('ItemCountry1')
  windowhome.clearProperty("ItemCountry2")
  windowhome.clearProperty("ItemCountry3")
  windowhome.clearProperty("ItemCountry4")
  if VidPlayer:
     CountryList=xbmc.getInfoLabel( "VideoPlayer.Country" ).replace("/",",")
    
  elif ContainerID:  
     CountryList=xbmc.getInfoLabel( "Container(%d).ListItem.Country" %(ContainerID) ).replace("/",",")
  else:
     CountryList=xbmc.getInfoLabel( "ListItem.Country" ).replace("/",",")
  
  if CountryList:
    CountryList=CountryList.split(",")
    if not CountryList:
      if VidPlayer:
        CountryList=xbmc.getInfoLabel( "VideoPlayer.Country" )    
      elif ContainerID:
        CountryList.append(xbmc.getInfoLabel( "Container(%d).ListItem.Country" %(ContainerID)))
      else:
        CountryList.append(xbmc.getInfoLabel( "ListItem.Country" ))
    idx=1
    for country in CountryList:
       Pays=country.strip()
       TradFrEn=Traduction.get(country.strip().lower())
       if TradFrEn:
         Pays=TradFrEn
       windowhome.setProperty('ItemCountry%d' %(idx),Pays)
       idx=idx+1
 